# Use a imagem oficial do PostgreSQL 12
FROM postgres:12

# Defina as variáveis de ambiente para configurar o PostgreSQL
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=postgres

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432

# Defina um volume para persistir os dados do PostgreSQL
VOLUME /var/lib/postgresql/data